# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KmCli < Formula
  desc "CLI tool for KM document operations"
  homepage "https://github.com/huanghao/mt-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.1/km-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "3adb12623602e40311cc161759909bbd7ab97a02470a39ec37933dde7ef53cf1"

      define_method(:install) do
        bin.install "km-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.1/km-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "2a39d9c82af3843eddcf4a26227b40d5ce8545c7ab84e724d95491e8f380b530"

      define_method(:install) do
        bin.install "km-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.1/km-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "ddc650f7cfcbff59163946c3b833abe307a0cc05be830be64715347ba1f945de"
      define_method(:install) do
        bin.install "km-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.1/km-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "bdf9dd7dbdb3fe671c7ada92da5ae682ac84e5c3b0f445fc7886ec0f533c1b2b"
      define_method(:install) do
        bin.install "km-cli"
      end
    end
  end

  test do
    system "#{bin}/km-cli", "version"
  end
end
