# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require "json"

class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def fetch(timeout: nil)
    token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
    raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required for private repo downloads" if token.to_s.empty?

    m = url.match(%r{^https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/([^/]+)$})
    raise CurlDownloadStrategyError, "unsupported GitHub release url: #{url}" unless m
    owner, repo, tag, filename = m[1], m[2], m[3], m[4]
    rel_json = JSON.parse(
      curl_output(
        "--header", "Authorization: token #{token}",
        "https://api.github.com/repos/#{owner}/#{repo}/releases/tags/#{tag}",
        timeout:
      ).stdout
    )
    asset = rel_json.fetch("assets", []).find { |a| a["name"] == filename }
    raise CurlDownloadStrategyError, "release asset not found: #{filename}" if asset.nil?
    asset_api_url = "https://api.github.com/repos/#{owner}/#{repo}/releases/assets/#{asset.fetch("id")}"

    ohai "Downloading #{url}"
    if cached_location.exist?
      puts "Already downloaded: #{cached_location}"
    else
      begin
        curl_download asset_api_url,
          "--header", "Authorization: token #{token}",
          "--header", "Accept: application/octet-stream",
          to: temporary_path, timeout:
      rescue ErrorDuringExecution
        raise CurlDownloadStrategyError, url
      end
      cached_location.dirname.mkpath
      temporary_path.rename(cached_location.to_s)
    end

    symlink_location.dirname.mkpath
    FileUtils.ln_s cached_location.relative_path_from(symlink_location.dirname), symlink_location, force: true
  end
end

class KmCli < Formula
  desc "CLI tool for KM document operations"
  homepage "https://github.com/huanghao/mt-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.3/km-cli_0.2.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d4ffee564c6e55dc176b23b10adcbd94c92f01ca96ec3babf6f11e28f6803473"

      define_method(:install) do
        bin.install "km-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.3/km-cli_0.2.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "77767ea10d139468823181483ee597ae2b231a812263a28e0ad2e8689cc787da"

      define_method(:install) do
        bin.install "km-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.3/km-cli_0.2.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "84bf3275a378edc9c39a6d5c5da9b25286b6569e8c7a281868d859652db67af2"
      define_method(:install) do
        bin.install "km-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/huanghao/mt-cli/releases/download/v0.2.3/km-cli_0.2.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d707bdce1025b51c88a5e9b6a4c2e0513d0a8e1457cbafd52a1813c64a8e4d85"
      define_method(:install) do
        bin.install "km-cli"
      end
    end
  end

  test do
    system "#{bin}/km-cli", "version"
  end
end
